#!/usr/bin/env python3
"""Operator signal voice — speak key status changes via TTS.

Usage (from project root):
    python scripts/speak.py "Work order complete"
    python scripts/speak.py --persona dm_narrator "Playtest ready"
    python scripts/speak.py --volume 0.3 "Tests passing"
    python scripts/speak.py --backend kokoro "Fallback test"
    python scripts/speak.py --list-personas

Backend priority:
    1. Chatterbox (GPU, CUDA) — higher quality, emotion control
    2. Kokoro (CPU, ONNX) — fast fallback if no GPU

Voice profile (default): Calm, grounded, neutral-operational.
    Mid-low pitch, clean texture, even cadence, controlled warmth.
    Optimized for sustained analytical listening during long sessions.

Called by the AI co-pilot to voice high-value signals:
    - Work order completion
    - Playtest ready
    - Test failures
    - Operator action required
"""

import argparse
import io
import struct
import sys
import tempfile
import wave
from pathlib import Path

# Project root = parent of scripts/
PROJECT_ROOT = Path(__file__).resolve().parent.parent
MODEL_PATH = str(PROJECT_ROOT / "models" / "kokoro" / "kokoro-v1.0.int8.onnx")
VOICES_PATH = str(PROJECT_ROOT / "models" / "kokoro" / "voices-v1.0.bin")

# Default volume: 50% — operator requested half volume
DEFAULT_VOLUME = 0.5

# Add project root to path for imports
sys.path.insert(0, str(PROJECT_ROOT))


# ---------------------------------------------------------------------------
# Volume attenuation
# ---------------------------------------------------------------------------

def _attenuate_wav(wav_bytes: bytes, volume: float) -> bytes:
    """Scale WAV audio amplitude by volume factor.

    Args:
        wav_bytes: Input WAV data
        volume: 0.0 (silent) to 1.0 (full volume)

    Returns:
        Volume-adjusted WAV bytes
    """
    if volume >= 1.0:
        return wav_bytes

    buf_in = io.BytesIO(wav_bytes)
    buf_out = io.BytesIO()

    with wave.open(buf_in, "rb") as wf_in:
        params = wf_in.getparams()
        raw = wf_in.readframes(params.nframes)

    if params.sampwidth != 2:
        # Only handle 16-bit PCM
        return wav_bytes

    # Unpack, scale, repack
    n_samples = len(raw) // 2
    samples = struct.unpack(f"<{n_samples}h", raw)
    scaled = [int(max(-32768, min(32767, s * volume))) for s in samples]
    raw_out = struct.pack(f"<{n_samples}h", *scaled)

    with wave.open(buf_out, "wb") as wf_out:
        wf_out.setparams(params)
        wf_out.writeframes(raw_out)

    return buf_out.getvalue()


# ---------------------------------------------------------------------------
# Backend: Chatterbox (GPU)
# ---------------------------------------------------------------------------

def _speak_chatterbox(text: str, persona: str) -> bytes:
    """Synthesize via Chatterbox TTS (GPU) with voice-cloned signal voice.

    Voice pipeline: Kokoro am_adam generates a reference clip (models/voices/signal_reference.wav),
    then Chatterbox clones that voice for all signal output. This gives us explicit male voice
    control with GPU-quality synthesis.

    Returns WAV bytes, or raises on failure.
    """
    from aidm.immersion.chatterbox_tts_adapter import ChatterboxTTSAdapter
    from aidm.schemas.immersion import VoicePersona

    # Reference clip: generated by Kokoro am_michael FULL model at native 24kHz
    # No downsample — matches Chatterbox's expected mel spectrogram input exactly.
    # Pipeline: Kokoro fp32 24kHz -> Chatterbox voice clone -> winsound
    ref_clip = str(PROJECT_ROOT / "models" / "voices" / "signal_reference_michael_24k.wav")

    # Voice Profile: Arbor (Chat Readback Mode)
    # Calm, grounded, neutral-operational. Mid-range, low-variance.
    # Optimized for sustained cognitive listening during long sessions.
    # Spec: steady pacing, limited emotional modulation, clean articulation,
    #        no theatrical rise/fall, mid-energy neutrality.
    _ARBOR = VoicePersona(
        persona_id="arbor",
        name="Arbor",
        voice_model="chatterbox",
        speed=0.88,
        pitch=1.0,
        exaggeration=0.15,
        reference_audio=ref_clip,
    )

    adapter = ChatterboxTTSAdapter()

    if not adapter.is_available():
        raise RuntimeError("Chatterbox not available")

    # Original tier: natural-sounding, respects voice cloning + exaggeration
    return adapter.synthesize(text, persona=_ARBOR, force_turbo=False)


# ---------------------------------------------------------------------------
# Backend: Kokoro (CPU fallback)
# ---------------------------------------------------------------------------

def _speak_kokoro(text: str, persona: str) -> bytes:
    """Synthesize via Kokoro TTS (CPU).

    Returns WAV bytes, or raises on failure.
    """
    from aidm.immersion.kokoro_tts_adapter import KokoroTTSAdapter

    adapter = KokoroTTSAdapter(
        model_path=MODEL_PATH,
        voices_path=VOICES_PATH,
    )

    if not adapter.is_available():
        raise RuntimeError("Kokoro not available")

    return adapter.synthesize(text, persona)


# ---------------------------------------------------------------------------
# Main speak function
# ---------------------------------------------------------------------------

def speak(text: str, persona: str = "dm_narrator", volume: float = DEFAULT_VOLUME, backend: str = "auto") -> bool:
    """Synthesize and play text.

    Args:
        text: Text to speak
        persona: Voice persona key
        volume: Volume level 0.0-1.0 (default 0.5)
        backend: "auto", "chatterbox", or "kokoro"

    Returns:
        True if audio played successfully
    """
    wav_bytes = None

    # Try backends in priority order
    if backend in ("auto", "chatterbox"):
        try:
            wav_bytes = _speak_chatterbox(text, persona)
        except Exception as e:
            if backend == "chatterbox":
                print(f"[speak] Chatterbox failed: {e}", file=sys.stderr)
                return False
            # auto mode: fall through to Kokoro

    if wav_bytes is None and backend in ("auto", "kokoro"):
        try:
            wav_bytes = _speak_kokoro(text, persona)
        except Exception as e:
            print(f"[speak] TTS failed: {e}", file=sys.stderr)
            return False

    if wav_bytes is None:
        print("[speak] No TTS backend available", file=sys.stderr)
        return False

    # Apply volume
    if volume < 1.0:
        wav_bytes = _attenuate_wav(wav_bytes, volume)

    return _play_wav(wav_bytes)


# ---------------------------------------------------------------------------
# Playback
# ---------------------------------------------------------------------------

def _play_wav(wav_bytes: bytes) -> bool:
    """Play WAV bytes through system audio."""
    # Windows: winsound (built-in)
    try:
        import winsound
        winsound.PlaySound(wav_bytes, winsound.SND_MEMORY)
        return True
    except ImportError:
        pass
    except Exception as e:
        print(f"[speak] winsound failed: {e}", file=sys.stderr)

    # Fallback: temp file + platform command
    try:
        with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as f:
            f.write(wav_bytes)
            tmp_path = f.name

        import subprocess
        import platform

        system = platform.system()
        if system == "Darwin":
            subprocess.run(["afplay", tmp_path], check=True)
        elif system == "Linux":
            subprocess.run(["aplay", tmp_path], check=True)
        else:
            subprocess.run(["start", "", tmp_path], shell=True, check=True)

        Path(tmp_path).unlink(missing_ok=True)
        return True
    except Exception as e:
        print(f"[speak] Playback failed: {e}", file=sys.stderr)
        return False


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def list_personas() -> None:
    """Print available voice personas from both backends."""
    print("Chatterbox (GPU):")
    try:
        from aidm.immersion.chatterbox_tts_adapter import ChatterboxTTSAdapter
        adapter = ChatterboxTTSAdapter()
        avail = adapter.is_available()
        for p in adapter.list_personas():
            print(f"  {p.persona_id:20s}  {p.name}")
        print(f"  Status: {'AVAILABLE' if avail else 'NOT AVAILABLE (no CUDA)'}")
    except Exception as e:
        print(f"  Error: {e}")

    print()
    print("Kokoro (CPU fallback):")
    try:
        from aidm.immersion.kokoro_tts_adapter import KokoroTTSAdapter
        adapter = KokoroTTSAdapter(model_path=MODEL_PATH, voices_path=VOICES_PATH)
        avail = adapter.is_available()
        for p in adapter.list_personas():
            print(f"  {p.persona_id:20s}  {p.name}  (voice: {p.voice_model})")
        print(f"  Status: {'AVAILABLE' if avail else 'NOT AVAILABLE'}")
    except Exception as e:
        print(f"  Error: {e}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Speak operator signals via TTS (Chatterbox GPU / Kokoro CPU)"
    )
    parser.add_argument("text", nargs="?", help="Text to speak")
    parser.add_argument(
        "--persona", default="dm_narrator",
        help="Voice persona (default: dm_narrator)"
    )
    parser.add_argument(
        "--volume", type=float, default=DEFAULT_VOLUME,
        help=f"Volume 0.0-1.0 (default: {DEFAULT_VOLUME})"
    )
    parser.add_argument(
        "--backend", choices=["auto", "chatterbox", "kokoro"], default="auto",
        help="TTS backend (default: auto)"
    )
    parser.add_argument(
        "--list-personas", action="store_true",
        help="List available voice personas"
    )
    args = parser.parse_args()

    if args.list_personas:
        list_personas()
        return

    if not args.text:
        text = sys.stdin.read().strip()
        if not text:
            parser.error("No text provided. Pass as argument or pipe to stdin.")
    else:
        text = args.text

    ok = speak(text, args.persona, args.volume, args.backend)
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
