"""M3 Audio Pipeline Schemas — Audio generation and playback contracts.

Defines data structures for the M3 audio pipeline:
- AudioTrack: Metadata for music and SFX tracks (generative or curated)
- AudioMood: Scene mood taxonomy for music selection
- AudioTierConfig: Hardware tier detection and adapter selection
- AudioAttribution: License and attribution tracking for curated assets

Reference: WO-M3-AUDIO-INT-01, EVAL-01 deliverables
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Literal


# ═════════════════════════════════════════════════════════════════════════
# Audio Mood Taxonomy
# ═════════════════════════════════════════════════════════════════════════


AudioMood = Literal["peaceful", "tense", "combat", "dramatic", "neutral"]
"""Scene mood categories for music selection.

Maps to ACE-Step prompts and curated track selection:
- peaceful: Tavern, village, forest, travel
- tense: Dungeon, cave, suspense, supernatural
- combat: Standard battle, boss/epic, skirmish
- dramatic: Revelation, climax, tragedy, loss
- neutral: Quiet ambient, minimal mood
"""


AudioEnvironment = Literal[
    "tavern", "village", "forest", "dungeon", "cave", "crypt",
    "battle", "boss_fight", "skirmish",
    "revelation", "tragedy", "triumph",
    "ambient", "unknown"
]
"""Environment subtypes for music sub-categorization.

Combined with AudioMood for precise music selection:
- (peaceful, tavern) → "peaceful acoustic folk, medieval tavern ambience"
- (tense, dungeon) → "ominous orchestral strings, dark dungeon atmosphere"
- (combat, boss_fight) → "intense orchestral climax, heavy percussion"
"""


# ═════════════════════════════════════════════════════════════════════════
# Audio Track Schema
# ═════════════════════════════════════════════════════════════════════════


@dataclass
class AudioTrack:
    """Audio track metadata (music or SFX, generative or curated).

    Used for both prep-time generation tracking and runtime playback.
    Supports generative (ACE-Step) and curated (Kevin MacLeod, Sonniss) sources.
    """

    kind: str
    """Semantic key identifying track purpose.

    Format for music: "music:{mood}:{environment}" (e.g., "music:peaceful:tavern")
    Format for SFX: "sfx:{category}:{subcategory}:{action}" (e.g., "combat:melee:sword:hit")
    Format for ambient: "ambient:{mood}:{environment}" (e.g., "ambient:tense:dungeon")
    """

    source_file: str
    """Relative path to audio file (from campaign asset directory).

    Examples:
    - "Music/peaceful_tavern_001.ogg"
    - "SFX/combat_sword_hit_01.ogg"
    """

    file_format: Literal["ogg", "wav", "mp3"] = "ogg"
    """Audio file format. Default: OGG Vorbis (EVAL-02, EVAL-03)."""

    # -------------------------------------------------------------------------
    # Generative Metadata
    # -------------------------------------------------------------------------

    generated: bool = False
    """True if track was generated by ACE-Step (or future generative SFX model)."""

    model_id: Optional[str] = None
    """Model identifier if generated (e.g., 'ace-step-3.5b')."""

    generation_prompt: Optional[str] = None
    """Prompt used for generative music (ACE-Step text-to-music input)."""

    generation_seed: Optional[int] = None
    """Random seed for deterministic generation (BL-017/018 compliance)."""

    # -------------------------------------------------------------------------
    # Curated Metadata
    # -------------------------------------------------------------------------

    curated_source: Optional[str] = None
    """Source name if curated (e.g., 'Kevin MacLeod', 'Sonniss GDC 2024')."""

    license: Optional[str] = None
    """License identifier (e.g., 'CC BY 3.0', 'CC0', 'Royalty-free')."""

    attribution: Optional[str] = None
    """Attribution string for CC BY assets (e.g., 'Kevin MacLeod (incompetech.com)')."""

    # -------------------------------------------------------------------------
    # Playback Metadata
    # -------------------------------------------------------------------------

    duration_seconds: float = 0.0
    """Track duration in seconds."""

    loop_start_ms: int = 0
    """Loop start point in milliseconds (for seamless looping)."""

    loop_end_ms: Optional[int] = None
    """Loop end point in milliseconds. None = loop entire track."""

    mood_intensity: float = 5.0
    """Mood intensity (0-10 scale) for crossfade matching.

    Used to smooth transitions between moods:
    - 0-3: Low intensity (ambient, peaceful)
    - 4-6: Medium intensity (tense, dramatic)
    - 7-10: High intensity (combat, boss fight)
    """

    # -------------------------------------------------------------------------
    # Variant Support (SFX)
    # -------------------------------------------------------------------------

    variant_group: Optional[str] = None
    """Variant group ID for SFX round-robin (e.g., 'combat:melee:sword:hit').

    Multiple tracks share same variant_group to support 3-5 variants per SFX key.
    """

    variant_index: Optional[int] = None
    """Variant index within group (0-4 for 3-5 variants)."""

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "kind": self.kind,
            "source_file": self.source_file,
            "file_format": self.file_format,
            "generated": self.generated,
            "model_id": self.model_id,
            "generation_prompt": self.generation_prompt,
            "generation_seed": self.generation_seed,
            "curated_source": self.curated_source,
            "license": self.license,
            "attribution": self.attribution,
            "duration_seconds": self.duration_seconds,
            "loop_start_ms": self.loop_start_ms,
            "loop_end_ms": self.loop_end_ms,
            "mood_intensity": self.mood_intensity,
            "variant_group": self.variant_group,
            "variant_index": self.variant_index,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "AudioTrack":
        """Create from dictionary."""
        return cls(
            kind=data.get("kind", ""),
            source_file=data.get("source_file", ""),
            file_format=data.get("file_format", "ogg"),  # type: ignore
            generated=data.get("generated", False),
            model_id=data.get("model_id"),
            generation_prompt=data.get("generation_prompt"),
            generation_seed=data.get("generation_seed"),
            curated_source=data.get("curated_source"),
            license=data.get("license"),
            attribution=data.get("attribution"),
            duration_seconds=data.get("duration_seconds", 0.0),
            loop_start_ms=data.get("loop_start_ms", 0),
            loop_end_ms=data.get("loop_end_ms"),
            mood_intensity=data.get("mood_intensity", 5.0),
            variant_group=data.get("variant_group"),
            variant_index=data.get("variant_index"),
        )


# ═════════════════════════════════════════════════════════════════════════
# Hardware Tier Configuration
# ═════════════════════════════════════════════════════════════════════════


AudioTier = Literal["baseline", "recommended", "enhanced"]
"""Hardware tier for audio generation.

- baseline: <6 GB VRAM or CPU-only → curated music/SFX only
- recommended: 6-8 GB VRAM → ACE-Step music generation, curated SFX
- enhanced: 8+ GB VRAM → ACE-Step music generation (faster), curated SFX

Reference: EVAL-04 Hardware Tier Mapping
"""


@dataclass
class AudioTierConfig:
    """Hardware tier configuration for audio pipeline.

    Detected at runtime to select music generation strategy.
    """

    tier: AudioTier
    """Detected hardware tier."""

    vram_gb: float
    """Detected VRAM in GB (0.0 if CPU-only)."""

    use_generative_music: bool
    """True if ACE-Step music generation is enabled (Recommended/Enhanced tiers)."""

    use_generative_sfx: bool = False
    """True if generative SFX is enabled. Currently always False (licensing blocked)."""

    user_override: Optional[Literal["curated_only", "generative_preferred"]] = None
    """User config override for music mode.

    - curated_only: Force curated library even on capable hardware
    - generative_preferred: Prefer ACE-Step if tier supports it (default)
    """

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "tier": self.tier,
            "vram_gb": self.vram_gb,
            "use_generative_music": self.use_generative_music,
            "use_generative_sfx": self.use_generative_sfx,
            "user_override": self.user_override,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "AudioTierConfig":
        """Create from dictionary."""
        return cls(
            tier=data.get("tier", "baseline"),  # type: ignore
            vram_gb=data.get("vram_gb", 0.0),
            use_generative_music=data.get("use_generative_music", False),
            use_generative_sfx=data.get("use_generative_sfx", False),
            user_override=data.get("user_override"),  # type: ignore
        )


# ═════════════════════════════════════════════════════════════════════════
# Attribution Ledger
# ═════════════════════════════════════════════════════════════════════════


@dataclass
class AudioAttribution:
    """Attribution record for curated audio asset.

    Tracks CC BY and royalty-free assets requiring attribution.
    """

    asset_id: str
    """Unique asset identifier (matches AudioTrack.source_file)."""

    asset_type: Literal["music", "sfx", "ambient"]
    """Asset type."""

    title: Optional[str] = None
    """Track title (for music)."""

    artist: Optional[str] = None
    """Artist/composer name."""

    source: str = ""
    """Source identifier (e.g., 'Kevin MacLeod', 'Sonniss GDC 2024', 'Freesound')."""

    license: str = ""
    """License identifier (e.g., 'CC BY 3.0', 'CC0', 'Royalty-free')."""

    url: Optional[str] = None
    """Source URL (for CC BY attribution requirements)."""

    requires_attribution: bool = True
    """True if license requires attribution (CC BY, royalty-free with attribution clause)."""

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "asset_id": self.asset_id,
            "asset_type": self.asset_type,
            "title": self.title,
            "artist": self.artist,
            "source": self.source,
            "license": self.license,
            "url": self.url,
            "requires_attribution": self.requires_attribution,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "AudioAttribution":
        """Create from dictionary."""
        return cls(
            asset_id=data.get("asset_id", ""),
            asset_type=data.get("asset_type", "music"),  # type: ignore
            title=data.get("title"),
            artist=data.get("artist"),
            source=data.get("source", ""),
            license=data.get("license", ""),
            url=data.get("url"),
            requires_attribution=data.get("requires_attribution", True),
        )

    def format_attribution(self) -> str:
        """Format attribution string for credits/ATTRIBUTION.txt.

        Returns:
            Human-readable attribution string
        """
        if not self.requires_attribution:
            return ""

        parts = []

        if self.title:
            parts.append(f'"{self.title}"')

        if self.artist:
            parts.append(f"by {self.artist}")

        if self.source:
            parts.append(f"({self.source})")

        if self.license:
            parts.append(f"— {self.license}")

        if self.url:
            parts.append(f"<{self.url}>")

        return " ".join(parts)


@dataclass
class AudioAttributionLedger:
    """Ledger of all audio attributions for a campaign.

    Tracks all CC BY and royalty-free assets requiring attribution.
    Generates ATTRIBUTION.txt for bundled assets.
    """

    attributions: List[AudioAttribution] = field(default_factory=list)
    """List of attribution records."""

    def add_attribution(self, attribution: AudioAttribution) -> None:
        """Add attribution record to ledger."""
        self.attributions.append(attribution)

    def get_attributions_by_type(
        self, asset_type: Literal["music", "sfx", "ambient"]
    ) -> List[AudioAttribution]:
        """Get all attributions of a specific type.

        Args:
            asset_type: Asset type to filter by

        Returns:
            List of matching attributions
        """
        return [a for a in self.attributions if a.asset_type == asset_type]

    def generate_attribution_text(self) -> str:
        """Generate ATTRIBUTION.txt content.

        Returns:
            Formatted attribution text for bundled assets
        """
        lines = ["=" * 80, "AUDIO ASSET ATTRIBUTIONS", "=" * 80, ""]

        # Music attributions
        music_attrs = self.get_attributions_by_type("music")
        if music_attrs:
            lines.append("MUSIC:")
            lines.append("")
            for attr in music_attrs:
                if attr.requires_attribution:
                    lines.append(f"  {attr.format_attribution()}")
            lines.append("")

        # SFX attributions
        sfx_attrs = self.get_attributions_by_type("sfx")
        if sfx_attrs:
            lines.append("SOUND EFFECTS:")
            lines.append("")
            for attr in sfx_attrs:
                if attr.requires_attribution:
                    lines.append(f"  {attr.format_attribution()}")
            lines.append("")

        # Ambient attributions
        ambient_attrs = self.get_attributions_by_type("ambient")
        if ambient_attrs:
            lines.append("AMBIENT AUDIO:")
            lines.append("")
            for attr in ambient_attrs:
                if attr.requires_attribution:
                    lines.append(f"  {attr.format_attribution()}")
            lines.append("")

        lines.append("=" * 80)
        return "\n".join(lines)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "attributions": [a.to_dict() for a in self.attributions],
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "AudioAttributionLedger":
        """Create from dictionary."""
        attributions = [
            AudioAttribution.from_dict(a) for a in data.get("attributions", [])
        ]
        return cls(attributions=attributions)
